FROM docker pull ghcr.io/puppeteer/puppeteer:23.10.1 # pulls the image that contains Puppeteer v16.1.0

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable


WORKDIR /usr/src/app

COPY package.json ./
RUN npm ci 
COPY
CMD
CMD ["node" ,"index.js"]